FROM golang:1.25-alpine AS builder
WORKDIR /build
COPY . .
WORKDIR /build/examples/blog
RUN go build -o /build/blog .

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /build/blog .
ENV PORT=9001
ENV HOST=0.0.0.0
EXPOSE 9001
CMD ["./blog"]
