FROM golang:1.24-alpine AS builder
WORKDIR /build
COPY . .
RUN go build -o shape-canvas .

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /build/shape-canvas .
COPY --from=builder /build/components ./components
COPY --from=builder /build/pages ./pages
ENV PORT=9000
ENV HOST=0.0.0.0
EXPOSE 9000
CMD ["./shape-canvas"]
